wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1668649573.829644
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.7.13
      5: 0.13.0
      8:
      - 5
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.001
step_size:
  desc: null
  value: 1
